@echo off
call :log_enter pENV

CALL sENV

SET PROJ_LABEL          =$SYS%
SET PROJ_NET            =$SYS_NET%

SET PROJ_CONT           =%MS_CONT%
SET PROJ_CONT_DATA_DIR  =%MS_CONT_DATA_DIR%
SET PROJ_CONT_DIR       =%MS_CONT_DIR%
SET PROJ_CONT_HOME_DIR  =%MS_CONT_HOME_DIR%
SET PROJ_HOST           =%MS_HOST%
SET PROJ_HOST_DIR       =%MS_HOST_DIR%
SET PROJ_IMG            =%MS_IMG%
SET PROJ_PASSWORD       =%MS_PASSWORD%
SET PROJ_PORT_EXT       =%MS_PORT_EXT%
SET PROJ_PORT_INT       =%MS_PORT_INT%
SET PROJ_USER           =%MS_USER%%
SET PROJ_VOL            =%MS_VOL%
SET PROJ_VOL_DIR        =%MS_VOL_DIR%

SET PROJ_DB_NAME        =%MS_DB_NAME%

call :log_exit pENV

